# Generated by Django 4.0.5 on 2022-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='diseños'),
        ),
        migrations.AddField(
            model_name='tatuaje',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tatuajes'),
        ),
    ]
