# Generated by Django 4.0.5 on 2022-06-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_diseno_imagen_tatuaje_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tatuaje',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
