# Generated by Django 4.0.5 on 2022-06-06 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_rename_descipcion_tatuaje_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
