# Generated by Django 4.0.5 on 2022-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_descipcion_diseno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tatuaje',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
