# Generated by Django 4.0.5 on 2022-06-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_diseno_nuevo_tatuaje_nuevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='nuevo',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='tatuaje',
            old_name='nuevo',
            new_name='principal',
        ),
    ]
