# Generated by Django 4.0.5 on 2022-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(default=False),
        ),
    ]
